# Nombre del workflow
name: ssh

# Cómo se activa este workflow
on:
  workflow_dispatch:

jobs:
  ssh:
    name: Sesión Interactiva 
    runs-on: depot-ubuntu-24.04-64 

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Instalar dependencias para compilar el kernel
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev git ccache
          
      - name: 3. Iniciar Sesión SSH con tmate
        # Esta acción pausa el workflow y te da acceso SSH.
        # El workflow continuará aquí hasta que cierres la sesión SSH.
        uses: mxschmitt/action-tmate@v3
        
