# Nombre del workflow
name: ssh

# Cómo se activa este workflow
on:
  workflow_dispatch:

jobs:
  ssh:
    name: Sesión Interactiva 
    runs-on: buildjet-32vcpu-ubuntu-2204

    steps:
    - name: Iniciar VS Code Tunnel y Pausar
      run: |
        # Descargar e instalar el CLI de VS Code
        echo "Instalando VS Code CLI..."
        curl -Lk 'https://update.code.visualstudio.com/latest/cli-linux-x64/stable' | sudo tar -C /usr/local/bin -xzf -
        
        # Iniciar el túnel en segundo plano
        echo "Iniciando el túnel de VS Code..."
        code tunnel --accept-server-license-terms &

        # Pausar el workflow para darte tiempo a conectar
        echo "################################################################################"
        echo "Túnel de VS Code iniciado. Busca en el log un enlace a vscode.dev o un mensaje para iniciar sesión."
        echo "El workflow se pausará por 6 horas. Debes cancelarlo manualmente cuando termines."
        echo "################################################################################"
        sleep 21600 # Pausa de 6 horas
        
