# Nombre del workflow
name: (EXPERIMENTAL) Build Unisoc GKI with Full Stock Config

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      # Pasos 1-4 (Sin cambios)
      - name: 1. Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends repo git bc build-essential curl g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
      - name: 2. Setup Repo Tool
        run: mkdir -p ~/bin && curl -s https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo && echo "$HOME/bin" >> $GITHUB_PATH
      - name: 3. Download Kernel Source
        run: |
          mkdir gki_kernel && cd gki_kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.4
          repo sync -c --no-tags --no-clone-bundle -j$(nproc --all)
      - name: 4. Integrate KernelSU-Next
        run: |
          cd gki_kernel/common
          git clone https://github.com/KernelSU-Next/KernelSU-Next.git KernelSU
          bash KernelSU/kernel/setup.sh

      # Paso 5: Preparar Archivos de Configuraci贸n (Sin cambios)
      - name: 5. Prepare Config Files
        run: |
          curl https://raw.githubusercontent.com/maxsteeel/gki-X6525/refs/heads/main/config_stock.txt > gki_kernel/common/arch/arm64/configs/stock_defconfig
          curl https://raw.githubusercontent.com/maxsteeel/gki-X6525/refs/heads/main/unisoc_modules.txt > gki_kernel/unisoc_modules.list
          curl https://raw.githubusercontent.com/maxsteeel/gki-X6525/refs/heads/main/ums9230-1h10-go.dts > gki_kernel/common/arch/arm64/boot/dts/sprd/ums9230-1h10-go.dts
          
          sed -i '/sp9860g-1h10.dtb/a \\t\t\tums9230-1h10-go.dtb \\' gki_kernel/common/arch/arm64/boot/dts/sprd/Makefile
          echo "DTS Makefile updated to include ums9230-1h10-go.dtb."
          

      # --- PASO 6: CORREGIDO Y SIMPLIFICADO ---
      - name: 6. Build The Kernel
        run: |
          cd gki_kernel
          
          > common/android/gki_aarch64_modules
          
          # 1. Creamos nuestra "hoja de pedido" con todas las instrucciones.
          cat <<EOF > common/build.config.unisoc
          . /home/runner/work/gki-X6525/gki-X6525/gki_kernel/common/build.config.common
          . /home/runner/work/gki-X6525/gki-X6525/gki_kernel/common/build.config.aarch64
          
          MAKE_GOALS="${MAKE_GOALS}
          Image.lz4
          "
          ABI_DEFINITION=android/abi_gki_aarch64.xml
          KMI_SYMBOL_LIST=android/abi_gki_aarch64
          ADDITIONAL_KMI_SYMBOL_LISTS="
          android/abi_gki_aarch64_unisoc
          android/abi_gki_aarch64_transsion
          "
          FILES="${FILES}
          arch/arm64/boot/Image.lz4
          "
          
          # Usar nuestra configuraci贸n, no la de GKI.
          DEFCONFIG=stock_defconfig
          
          # Desactivar TODAS las verificaciones de KMI.
          KMI_ENFORCED=0
          TRIM_NONLISTED_KMI=0
          KMI_SYMBOL_LIST_STRICT_MODE=0
          
          # Usar nuestra lista de m贸dulos como la verdad absoluta.
          MODULES_ORDER=android/gki_aarch64_modules
          KERNEL_CMDLINE="cpuidle.off=1"
          
          # Opciones de optimizaci贸n.
          LTO=thin
          EOF
          
          # 2. Le entregamos la hoja de pedido directamente al script.

          BUILD_CONFIG=common/build.config.unisoc build/build.sh

      # Paso 7: Subir los artefactos
      - name: 7. Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Unisoc-GKI-Next-Build
          path: gki_kernel/out/android12-5.4/dist/
          
